// <auto-generated />
namespace AspNetIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addArticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addArticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201804221947016_addArticle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
